### ISSUE TITLE
MBG HD Texture Pack doesn't upscale the interior textures.

### ISSUE THREAD

**Issue by BlastedMarble** [PlatinumTeam/PlatinumQuest#82]
![screenshot_00010](https://user-images.githubusercontent.com/42791880/109436403-35f1d180-79d4-11eb-9277-92582f43dbf7.png)
As you can see from the screenshot above, when loading the MBG HD texture pack, only the start and end pads, the skybox, and the gems have textures upscaled to HD. The grid and trim texture are not upscaled.

**Comment by HiGuyMB** [comment]
Switch to material texture quality: high. Does it work then?

**Comment by BlastedMarble** [comment]
I set the material quality to high and the interior textures actually upscaled. So they work. Thank you.
